apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: eu-south-1
  version: "1.35"

nodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1 
    maxSize: 2
    volumeSize: 20
    volumeType: gp3
    labels: 
      purpose: dev
      team: java
    taints:
      - key: "dedicated"
        value: "dev"
        effect: "PreferNoSchedule"
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
    ssh:
      allow: false 

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit","authenticator","controllerManager","scheduler"]
